<a href="https://colab.research.google.com/github/LokeshVadlamudi/DeepLearningClass/blob/master/kerasBooleanCrossEntropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
from keras.models import Model, load_model
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers
import tensorflow as tf

In [0]:
df = pd.read_csv('/content/drive/My Drive/creditcard.csv')

In [13]:
df.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [7]:
df.shape

(284807, 31)

In [8]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [11]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [0]:
df['Time'] = StandardScaler().fit_transform(df['Time'].values.reshape(-1,1))
df['Amount'] = StandardScaler().fit_transform(df['Amount'].values.reshape(-1,1))

In [0]:
input = df.drop(columns=['Class'])
output = df['Class']

In [21]:
input

            Time         V1         V2  ...       V27       V28    Amount
0      -1.996583  -1.359807  -0.072781  ...  0.133558 -0.021053  0.244964
1      -1.996583   1.191857   0.266151  ... -0.008983  0.014724 -0.342475
2      -1.996562  -1.358354  -1.340163  ... -0.055353 -0.059752  1.160686
3      -1.996562  -0.966272  -0.185226  ...  0.062723  0.061458  0.140534
4      -1.996541  -1.158233   0.877737  ...  0.219422  0.215153 -0.073403
...          ...        ...        ...  ...       ...       ...       ...
284802  1.641931 -11.881118  10.071785  ...  0.943651  0.823731 -0.350151
284803  1.641952  -0.732789  -0.055080  ...  0.068472 -0.053527 -0.254117
284804  1.641974   1.919565  -0.301254  ...  0.004455 -0.026561 -0.081839
284805  1.641974  -0.240440   0.530483  ...  0.108821  0.104533 -0.313249
284806  1.642058  -0.533413  -0.189733  ... -0.002415  0.013649  0.514355

[284807 rows x 30 columns]

In [23]:
input.shape

(284807, 30)

In [22]:
output

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [24]:
output.shape

(284807,)

In [0]:
X_train,X_test,y_train,y_test = train_test_split(input,output,test_size=.2,random_state=0)

In [26]:
X_train.shape

(227845, 30)

In [27]:
y_train

68806     0
40018     0
250360    0
234820    0
10001     0
         ..
211543    0
86293     0
122579    0
152315    0
117952    0
Name: Class, Length: 227845, dtype: int64

In [28]:
X_test

            Time        V1        V2  ...       V27       V28    Amount
183484  0.652946 -0.323334  1.057455  ...  0.108494  0.161139 -0.193306
255448  1.314460 -0.349718  0.932619  ...  0.076830  0.175562 -0.345313
244749  1.214140 -1.614711 -2.406570  ...  0.286285  0.437322  0.030587
63919  -0.924166 -2.477184  0.860613  ... -0.510060 -0.660533  0.878181
11475  -1.577551  1.338831 -0.547264  ... -0.002769  0.003272 -0.333239
...          ...       ...       ...  ...       ...       ...       ...
236778  1.139974 -1.227033  0.987207  ...  0.011475  0.027130 -0.272068
127073 -0.349853  1.250596  0.159552  ... -0.022217  0.006667 -0.328641
208502  0.891490  1.125402 -2.288998  ... -0.240867 -0.007494  1.978494
263323  1.391489  2.064857  0.285198  ... -0.103162 -0.061743 -0.341435
246221  1.227090  2.351382 -1.325226  ...  0.007269 -0.051634 -0.293258

[56962 rows x 30 columns]

In [0]:
from keras.models import Sequential
from keras.layers import Dense,Dropout, Flatten
from keras.optimizers import Adam,sgd
from sklearn.metrics import mean_absolute_error
from keras import layers, metrics
import keras

In [35]:
!pip3 install 'gast==0.2.2'
try:
  %tensorflow_version 2.x
except Exception:
  pass

Collecting gast==0.2.2
  Downloading https://files.pythonhosted.org/packages/4e/35/11749bf99b2d4e3cceb4d55ca22590b0d7c2c62b9de38ac4a4a7f4687421/gast-0.2.2.tar.gz
Building wheels for collected packages: gast
  Building wheel for gast (setup.py) ... done
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=7fe591dae4b84cf9aeafd15f32125903c6ef9d6c29475f2b085a1d039cd5668c
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow 2.2.0rc3 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
Installing collected packages: gast
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
Successfully installed gast-0.2.2

In [0]:

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [0]:
def runAlgo(X_train,X_test,y_train,y_test):
    logi = Sequential()
    logi.add(Dense(303, activation="relu",input_shape=(30,)))
    logi.add(Dropout(0.3))
    logi.add(Dense(9, activation="relu"))
    logi.add(Dropout(0.1))
    logi.add(Dense(3, activation="relu"))
    logi.add(Dense(1,activation='sigmoid'))
    logi.compile(loss='binary_crossentropy', optimizer=sgd(), metrics=['accuracy'])
    logi.fit(X_train, y_train, epochs=10)
    a = logi.evaluate(X_test, y_test)
    return a

In [42]:
runAlgo(X_train,X_test,y_train,y_test)

Epoch 1/10
227845/227845 [==============================] - 10s 45us/step - loss: 0.0136 - accuracy: 0.9983
Epoch 2/10
227845/227845 [==============================] - 10s 45us/step - loss: 0.0051 - accuracy: 0.9983
Epoch 3/10
227845/227845 [==============================] - 10s 46us/step - loss: 0.0045 - accuracy: 0.9983
Epoch 4/10
227845/227845 [==============================] - 10s 46us/step - loss: 0.0043 - accuracy: 0.9983
Epoch 5/10
227845/227845 [==============================] - 10s 46us/step - loss: 0.0042 - accuracy: 0.9983
Epoch 6/10
227845/227845 [==============================] - 11s 46us/step - loss: 0.0041 - accuracy: 0.9983
Epoch 7/10
227845/227845 [==============================] - 10s 46us/step - loss: 0.0040 - accuracy: 0.9983
Epoch 8/10
227845/227845 [==============================] - 11s 46us/step - loss: 0.0040 - accuracy: 0.9983
Epoch 9/10
227845/227845 [==============================] - 11s 46us/step - loss: 0.0039 - accuracy: 0.9983
Epoch 10/10
227845/227845 [==============================] - 11s 46us/step - loss: 0.0039 - accuracy: 0.9983
56962/56962 [==============================] - 1s 20us/step

[0.0035302081748870063, 0.9982268810272217]